export const difficultyOrder = ["easy", "normal", "medium", "hard"] as const;

export type Difficulty = (typeof difficultyOrder)[number];

export const difficultyLabels: Record<Difficulty, string> = {
  easy: "かんたん",
  normal: "ふつう",
  medium: "むずかしい",
  hard: "はかせレベル",
};

export const difficultyIcons: Record<Difficulty, string> = {
  easy: "🟢",
  normal: "🔵",
  medium: "🟡",
  hard: "🔴",
};

export const difficultyTotals: Record<Difficulty, number> = {
  easy: 50,
  normal: 25,
  medium: 15,
  hard: 10,
};

type AnimalMetadata = {
  difficulty: Difficulty;
  extraHint: string;
};

export const animalMetadata: Record<string, AnimalMetadata> = {
  lion: { difficulty: "easy", extraHint: "ねこの なかまで、おおきな こえで ほえるよ" },
  elephant: { difficulty: "easy", extraHint: "きばが ながく のびる なかまも いるよ" },
  giraffe: { difficulty: "easy", extraHint: "まえあしも うしろあしも ながいよ" },
  zebra: { difficulty: "easy", extraHint: "たてがみが みじかく たっているよ" },
  panda: { difficulty: "easy", extraHint: "まるい みみと みじかい しっぽ" },
  koala: { difficulty: "easy", extraHint: "おなかの ふくろで こどもを そだてるよ" },
  kangaroo: { difficulty: "easy", extraHint: "まえあしは みじかく、むねの まえに かまえるよ" },
  gorilla: { difficulty: "easy", extraHint: "おとなの おすは せなかが ぎんいろになるよ" },
  monkey: { difficulty: "easy", extraHint: "なかまと いろいろな こえで はなしあうよ" },
  tiger: { difficulty: "easy", extraHint: "ひとりで こうどうすることが おおいよ" },
  bear: { difficulty: "easy", extraHint: "ふゆに ながく ねむる なかまも いるよ" },
  "polar-bear": { difficulty: "easy", extraHint: "あしの うらにも けが はえているよ" },
  hippo: { difficulty: "easy", extraHint: "めと みみが あたまの うえに ついているよ" },
  rhino: { difficulty: "easy", extraHint: "めは あまり よくないけれど、みみが いいよ" },
  crocodile: { difficulty: "easy", extraHint: "かたい うろこで からだが おおわれているよ" },
  camel: { difficulty: "easy", extraHint: "ながい まつげで すなを ふせぐよ" },
  horse: { difficulty: "easy", extraHint: "みみを うごかして きもちを つたえるよ" },
  cow: { difficulty: "easy", extraHint: "ひづめが ふたつに わかれているよ" },
  pig: { difficulty: "easy", extraHint: "しっぽが くるんと まがっているよ" },
  sheep: { difficulty: "easy", extraHint: "あかちゃんは おかあさんの こえを おぼえるよ" },
  goat: { difficulty: "easy", extraHint: "つのが はえる なかまも いるよ" },
  rabbit: { difficulty: "easy", extraHint: "まえばが ずっと のびつづけるよ" },
  dog: { difficulty: "easy", extraHint: "いろいろな しごとで ひとを たすけるよ" },
  cat: { difficulty: "easy", extraHint: "よるでも よく みえる めを もつよ" },
  squirrel: { difficulty: "easy", extraHint: "きの うえに すを つくる なかまも いるよ" },
  mouse: { difficulty: "easy", extraHint: "ひげで まわりを さぐるよ" },
  fox: { difficulty: "easy", extraHint: "よるに うごく なかまが おおいよ" },
  raccoon: { difficulty: "easy", extraHint: "きのぼりが とくいだよ" },
  deer: { difficulty: "easy", extraHint: "おおきな みみで ちいさな おとを きくよ" },
  boar: { difficulty: "easy", extraHint: "するどい きばを もつ おすも いるよ" },
  wolf: { difficulty: "easy", extraHint: "はなと みみが とても するどいよ" },
  cheetah: { difficulty: "easy", extraHint: "めから くちへ くろい せんが のびているよ" },
  leopard: { difficulty: "easy", extraHint: "よるに ひとりで かりを することが おおいよ" },
  hyena: { difficulty: "normal", extraHint: "メスが むれの リーダーになるよ" },
  sloth: { difficulty: "easy", extraHint: "からだの けに みどりの こけが はえることが あるよ" },
  anteater: { difficulty: "easy", extraHint: "おおきな まえあしの つめで すを こわすよ" },
  armadillo: { difficulty: "normal", extraHint: "つよい つめで じめんに あなを ほるよ" },
  meerkat: { difficulty: "normal", extraHint: "かぞくで いっしょに こどもを そだてるよ" },
  otter: { difficulty: "easy", extraHint: "ゆびの あいだに みずかきが あるよ" },
  seal: { difficulty: "easy", extraHint: "こおりや すなはまの うえで やすむよ" },
  penguin: { difficulty: "easy", extraHint: "なかまと たくさん あつまって くらすよ" },
  dolphin: { difficulty: "easy", extraHint: "あたまの あなから いきを するよ" },
  whale: { difficulty: "easy", extraHint: "こどもは おかあさんの おちちを のむよ" },
  shark: { difficulty: "easy", extraHint: "からだの よこに えらの すじが みえるよ" },
  octopus: { difficulty: "easy", extraHint: "まわりに あわせて からだの いろを かえるよ" },
  jellyfish: { difficulty: "easy", extraHint: "ながい しょくしゅに どくばりが ある なかまも いるよ" },
  "sea-turtle": { difficulty: "easy", extraHint: "まえあしが おおきな ひれの かたちだよ" },
  frog: { difficulty: "easy", extraHint: "ながい したで むしを つかまえるよ" },
  snake: { difficulty: "easy", extraHint: "あごを おおきく ひらいて えものを のみこむよ" },
  tortoise: { difficulty: "normal", extraHint: "あしが ふとく、じめんを しっかり あるくよ" },
  owl: { difficulty: "easy", extraHint: "かおの まわりの はねが まるく ならんでいるよ" },
  eagle: { difficulty: "normal", extraHint: "たかい ところに おおきな すを つくるよ" },
  flamingo: { difficulty: "easy", extraHint: "くちばしを さかさにして みずの えさを こすよ" },
  peacock: { difficulty: "normal", extraHint: "あたまに かんむりのような はねが あるよ" },
  parrot: { difficulty: "normal", extraHint: "かたい くちばしで きのみを わるよ" },
  chicken: { difficulty: "easy", extraHint: "じめんを あしで かいて えさを さがすよ" },
  duck: { difficulty: "normal", extraHint: "おしりを ふりながら あるくよ" },
  swan: { difficulty: "normal", extraHint: "おおきな つばさで みずの うえから とびたつよ" },
  bee: { difficulty: "normal", extraHint: "おしりに はりを もつ はたらきばちが いるよ" },
  butterfly: { difficulty: "easy", extraHint: "あたまに 2ほんの しょっかくが あるよ" },
  binturong: { difficulty: "medium", extraHint: "よるに きの うえを ゆっくり あるくよ" },
  "red-panda": { difficulty: "normal", extraHint: "まえあしで たべものを じょうずに もてるよ" },
  tapir: { difficulty: "normal", extraHint: "まえあしの ゆびは 4ほん、うしろあしは 3ぼんだよ" },
  capybara: { difficulty: "normal", extraHint: "ゆびの あいだに みずかきが あるよ" },
  alpaca: { difficulty: "normal", extraHint: "うえの まえばが ないよ" },
  llama: { difficulty: "normal", extraHint: "おこると つばを とばすことが あるよ" },
  orangutan: { difficulty: "normal", extraHint: "まいばん きの うえに ねどこを つくるよ" },
  chimpanzee: { difficulty: "normal", extraHint: "わらったり おこったり、かおで きもちを みせるよ" },
  gibbon: { difficulty: "medium", extraHint: "しっぽが ない さるの なかまだよ" },
  mandrill: { difficulty: "medium", extraHint: "おしりも あかや あおの いろを しているよ" },
  baboon: { difficulty: "normal", extraHint: "じめんの うえを 4ほんあしで あるくことが おおいよ" },
  okapi: { difficulty: "normal", extraHint: "おおきな みみを うごかして おとを さがすよ" },
  wildebeest: { difficulty: "normal", extraHint: "あごの したに ながい ひげが あるよ" },
  buffalo: { difficulty: "normal", extraHint: "どろあびを して からだを ひやすよ" },
  pronghorn: { difficulty: "medium", extraHint: "つのの そとがわが まいとし ぬけかわるよ" },
  gerenuk: { difficulty: "medium", extraHint: "みずを あまり のまず、はっぱから とるよ" },
  fennec: { difficulty: "normal", extraHint: "あしの うらの けが あつい すなから まもるよ" },
  mongoose: { difficulty: "medium", extraHint: "かぞくで くらす なかまも いるよ" },
  badger: { difficulty: "medium", extraHint: "よるに じめんの むしなどを さがすよ" },
  skunk: { difficulty: "normal", extraHint: "しっぽを たかく あげて てきを おどすよ" },
  porcupine: { difficulty: "normal", extraHint: "きの かわや ねっこを かじって たべるよ" },
  pangolin: { difficulty: "medium", extraHint: "ながい したで アリを たべるよ" },
  wombat: { difficulty: "medium", extraHint: "つよい まえあしで おおきな あなを ほるよ" },
  "tasmanian-devil": { difficulty: "medium", extraHint: "しろい むなもようが ある なかまも いるよ" },
  platypus: { difficulty: "normal", extraHint: "めを とじて、くちばしで えものを さがすよ" },
  echidna: { difficulty: "medium", extraHint: "てきが くると じめんに もぐるよ" },
  manatee: { difficulty: "medium", extraHint: "まえあしのような ひれに つめが ある なかまも いるよ" },
  dugong: { difficulty: "medium", extraHint: "まえあしの ひれには つめが ないよ" },
  narwhal: { difficulty: "medium", extraHint: "せなかに おおきな ひれが ないよ" },
  walrus: { difficulty: "medium", extraHint: "おおきな からだに ぶあつい しぼうが あるよ" },
  fossa: { difficulty: "hard", extraHint: "まえむきの まま きから おりることが できるよ" },
  kinkajou: { difficulty: "hard", extraHint: "よるに きの うえで えさを さがすよ" },
  "naked-mole-rat": { difficulty: "hard", extraHint: "くちを とじたまま まえばで つちを ほれるよ" },
  "aye-aye": { difficulty: "hard", extraHint: "よるに おおきな めで えさを さがすよ" },
  saiga: { difficulty: "hard", extraHint: "おすだけに うすい いろの つのが あるよ" },
  shoebill: { difficulty: "hard", extraHint: "おおきな つばさで ゆっくり とぶよ" },
  kakapo: { difficulty: "hard", extraHint: "きの みきに のぼるのが とくいだよ" },
  quokka: { difficulty: "hard", extraHint: "よるに くさや はっぱを たべるよ" },
  sifaka: { difficulty: "hard", extraHint: "ながい しっぽで バランスを とるよ" },
  markhor: { difficulty: "hard", extraHint: "ふゆになると ながい けが ふさふさになるよ" },
};
